config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  resources :log_entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "log_entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :log_entries
end

app/models/log_entry.rb
class LogEntry < ApplicationRecord
  belongs_to :category
  validates :calories, :proteins, :fats, :carbohydrates, :meal_type, :category_id, presence: true

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @log_entries = LogEntry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_log_entry, only: %i[ show edit update destroy ]

  # GET /log_entries or /log_entries.json
  def index
    @log_entries = LogEntry.where("created_at >= ?", Date.today)
  end

  # GET /log_entries/1 or /log_entries/1.json
  def show
  end

  # GET /log_entries/new
  def new
    @log_entry = LogEntry.new
  end

  # GET /log_entries/1/edit
  def edit
  end

  # POST /log_entries or /log_entries.json
  def create
    @log_entry = LogEntry.new(log_entry_params)

    respond_to do |format|
      if @log_entry.save
        format.html { redirect_to log_entry_url(@log_entry), notice: "Log entry was successfully created." }
        format.json { render :show, status: :created, location: @log_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_entries/1 or /log_entries/1.json
  def update
    respond_to do |format|
      if @log_entry.update(log_entry_params)
        format.html { redirect_to log_entry_url(@log_entry), notice: "Log entry was successfully updated." }
        format.json { render :show, status: :ok, location: @log_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_entries/1 or /log_entries/1.json
  def destroy
    @log_entry.destroy

    respond_to do |format|
      format.html { redirect_to log_entries_url, notice: "Log entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_entry
      @log_entry = LogEntry.find(params[:id]) 
    end

    # Only allow a list of trusted parameters through.
    def log_entry_params
      params.require(:log_entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @log_entries.each do |day, log_entries| %>
    <h3 class="is-size-4 has-text-bold mb-4 has-text-centered mt-6">
      <strong>Nutrient breakdown</strong> for <%= day %>
    </h3>

    <nav class="level is-mobile">
      <div class="level-item has-text-centered">
        <div>
          <h4 class="heading">Calories</h4>
          <p class="title"><%= log_entries.pluck(:calories).sum %>kcal</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <h4 class="heading">Proteins</h4>
          <p class="title"><%= log_entries.pluck(:proteins).sum %>g</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <h4 class="heading">Carbohydrates</h4>
          <p class="title"><%= log_entries.pluck(:carbohydrates).sum %>g</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <h4 class="heading">Fats</h4>
          <p class="title"><%= log_entries.pluck(:fats).sum %>g</p>
        </div>
      </div>
    </nav>

    <% log_entries.each do |log_entry| %> <%= link_to log_entry_path(log_entry) do %>
    <div class="card">
      <div class="card-content">
        <strong><%= log_entry.meal_type %></strong>
      </div>
    </div>
    <% end %> <% end %> <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css"
    />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> <%=
    javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %> <% if notice.present? %>
      <p class="notification is-link is-light"><%= notice %></p>
      <% end %> <% if alert.present? %>
      <p class="notification is-danger is-light"><%= alert %></p>
      <% end %> <%= yield %>
    </div>
  </body>
</html>

app/views/log_entries/_form.html.erb
<%= form_with(model: log_entry) do |form| %> <% if log_entry.errors.any? %>
<div class="message is-danger">
  <div class="message-header">
    <p>
      <%= pluralize(log_entry.errors.count, "error") %> prohibited this log
      entry from being saved:
    </p>
  </div>
  <div class="message-body">
    <ul>
      <% log_entry.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div>
  <%= form.label :meal_type, class: "label" %> <%= form.text_field:meal_type,
  class: "input" %>
</div>

<div>
  <%= form.label :calories, class: "label" %> <%= form.number_field:calories,
  class: "input" %>
</div>

<div>
  <%= form.label :proteins, class: "label" %> <%= form.number_field:proteins,
  class: "input" %>
</div>

<div class="field">
  <%= form.label :category, class: "label" %>
  <div class="select">
    <%= form.select :category_id, Category.all.collect {|cat| [cat.title,
    cat.id]}%>
  </div>
</div>

<div>
  <%= form.label :carbohydrates, class: "label" %> <%=
  form.number_field:carbohydrates, class: "input" %>
</div>

<div>
  <%= form.label :fats, class: "label" %> <%= form.number_field:fats, class:
  "input" %>
</div>

<div class="actions pt-4"><%= form.submit class: "button is-success" %></div>
<% end %>

app/views/log_entries/_log_entry.html.erb
<div id="<%= dom_id log_entry %>" class="column is-one-quarter">
  <div class="card">
    <header class="card-header">
      <h1 class="card-header-title">
        <%= log_entry.meal_type %> | <%= log_entry.category.title if log_entry.category.present? %>
      </h1>
    </header>

    <section class="card-content">
      <div class="content">
        <p>
          <span class="has-text-weight-bold">Calories:</span> <%=
          log_entry.calories %>
        </p>
        <p>
          <span class="has-text-weight-bold">Proteins:</span> <%=
          log_entry.proteins %>g
        </p>
        <p>
          <span class="has-text-weight-bold">Carbohydrates:</span> <%=
          log_entry.carbohydrates %>g
        </p>
        <p>
          <span class="has-text-weight-bold">Fats:</span> <%= log_entry.fats %>g
        </p>
        <p class="is-italic">
          Logged <%= time_ago_in_words(log_entry.created_at) %>
        </p>
      </div>
    </section>
    <footer class="card-footer">
      <%= link_to "Show", log_entry_path(log_entry), class: "card-footer-item"
      %> <%= link_to "Edit", edit_log_entry_path(log_entry), class:
      "card-footer-item" %> <%= link_to "Delete", log_entry_path(log_entry),
      data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" }, class:
      "card-footer-item" %>
    </footer>
  </div>
</div>

app/views/log_entries/edit.html.erb
<div class="section">
  <h1 class="title">Editing log entry</h1>
  <%= render "form", log_entry: @log_entry %>

  <br />

  <div>
    <%= link_to "Show this log entry", @log_entry %> | <%= link_to "Back to log
    entries", log_entries_path %>
  </div>
</div>

app/views/log_entries/index.html.erb
<div class="section">
  <h1 class="title">Log entries &ndash; <%= DateTime.now.to_fs(:short) %></h1>

  <div id="log_entries" class="is-flex">
    <% @log_entries.each do |log_entry| %> <%= render log_entry %> <% end %>
  </div>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class: "button is-link
  is-outlined is-centered" %>
</div>

app/views/log_entries/new.html.erb
<div class="section">
  <h1 class="title">New log entry</h1>

  <%= render "form", log_entry: @log_entry %>

  <br />

  <div><%= link_to "Back to log entries", log_entries_path %></div>
</div>

app/views/log_entries/show.html.erb
<%= render @log_entry %>

<div class="is-flex is-justify-content-center">
  <%= link_to "Back to log entries", log_entries_path %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 48 48"
      width="30"
      height="30"
    >
      <title>rice</title>
      <g class="nc-icon-wrapper">
        <path
          d="M37.812,15.279a1,1,0,0,1-.831-1.554l8.187-12.28a1,1,0,0,1,1.664,1.11h0L38.646,14.834A1,1,0,0,1,37.812,15.279Z"
          fill="#bf8c5a"
        ></path>
        <path
          d="M30.43,15a.986.986,0,0,1-.336-.059,1,1,0,0,1-.606-1.277l3.571-10a1,1,0,0,1,1.909.6c-.008.026-.017.051-.027.076l-3.57,10A1,1,0,0,1,30.43,15Z"
          fill="#bf8c5a"
        ></path>
        <path
          d="M43,20a6.987,6.987,0,0,0-11.062-5.689,6.972,6.972,0,0,0-8.568-2.794,6.986,6.986,0,0,0-11.693,1.5A7,7,0,0,0,12,27H37v-.08A7.006,7.006,0,0,0,43,20Z"
          fill="#e3e3e3"
        ></path>
        <path
          d="M46,23H2a1,1,0,0,0-1,1A23.055,23.055,0,0,0,14.458,44.909a1,1,0,0,0,.416.091H33.126a1,1,0,0,0,.416-.091A23.055,23.055,0,0,0,47,24,1,1,0,0,0,46,23Z"
          fill="#bf8c5a"
        ></path>
        <circle cx="8" cy="9" r="1" fill="#aeaeae"></circle>
        <circle cx="23" cy="6" r="1" fill="#aeaeae"></circle>
        <circle cx="18" cy="17" r="1" fill="#aeaeae"></circle>
      </g>
    </svg>
    <h3 class="title is-4 pl-2">Foodlog</h3>
    <% end %>

    <a
      role="button"
      class="navbar-burger navbar-end"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbarBasicExample"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start"></div>

    <div class="navbar-item">
      <div class="buttons">
        <%= link_to "Create new entry", new_log_entry_path, class: "button
        is-success" %>
      </div>
    </div>
  </div>
</nav>